import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "../components/themes/providers";
import { SessionProvider } from "next-auth/react"
import NavBar from "@/components/custom/NavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
        <Providers>
          <NavBar/>
          {children}
        </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
